services:
  frontend:
    container_name: shblog-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    restart: always
    environment:
      - NODE_ENV=production
